zone: zh_cn
default: monitor
apinto:
  - "http://127.0.0.1:9400"
port: 8081
filter_forwarded: false
user_details:
  type: file
  file: ./account.yml
professions:

  - name: services
    profession: service
    i18n_name:
      zh_cn: 上游服务
      en_us: upstream services
  - name: discoveries
    profession: discovery
    i18n_name:
      zh_cn: 服务发现
      en_us: discoveries
  - name: auths
    profession: auth
    i18n_name:
      zh_cn: 鉴权
      en_us: auths
  - name: outputs
    profession: output
    i18n_name:
      zh_cn: 输出
      en_us: outputs