id: "upstream-2.apinto.com"
name: "upstream-2"
cname: "上游服务-2"
resume: "配置上游服务信息，通过API绑定，实现完整转发流程。支持IP Hash、带权轮询等负载均衡算法，合理分配上游服务压力，保证上游服务稳定性。"
version: "v1.0.0"
icon: "上游服务.png"
driver: "dynamic.apinto.com"
type: 1 #0为框架模块 1为核心模块 2为内置模块 3为非内置
auto: true
front: upstream
navigation: "navigation.upstream"
group_id: "core_module"
define:  # 动态模块定义
  profession: service
  drivers:
    - name: http
      title: TCP
  skill: Upstream
  fields:
    - name: title           # 定义从响应中对应字段中获取显示值
      title: 名称
    - name: id
      title: ID
    - name: driver
      title: 驱动名称
    - name: description
      title: 描述
  render:
    http: