# .goreleaser.yml
builds:
  - id: apinto-dashboard
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "6"
    gomips:
      - hardfloat
    goamd64:
      - v1
    targets:
      - linux_arm64
      - linux_amd64
      - linux_386
      - darwin_arm64
      - darwin_amd64
    dir: ./app/apinto-dashboard
    main: .
    binary: apinto-dashboard
    builder: go
    gobinary: go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
archives:
  - id: default
    format: tar.gz
    wrap_in_directory: apinto-dashboard
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: 'builds/account.yml'
        dst: account.yml
      - src: 'builds/config.yml'
        dst: config.yml
      - src: 'builds/Dockerfile'
        dst: Dockerfile
      - src: 'builds/static/*'
        dst: /static
        strip_parent: true
release:
  name_template: "{{ .Tag }}"
  mode: append