// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Service_ModuleInfo_FullMethodName            = "/proto.Service/ModuleInfo"
	Service_Request_FullMethodName               = "/proto.Service/Request"
	Service_MiddlewaresRequest_FullMethodName    = "/proto.Service/MiddlewaresRequest"
	Service_MiddlewaresResponse_FullMethodName   = "/proto.Service/MiddlewaresResponse"
	Service_CheckMiddlewareForApi_FullMethodName = "/proto.Service/CheckMiddlewareForApi"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	ModuleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfos, error)
	Request(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	MiddlewaresRequest(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error)
	MiddlewaresResponse(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error)
	CheckMiddlewareForApi(ctx context.Context, in *MiddlewareInfoRequest, opts ...grpc.CallOption) (*MiddlewareInfoResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) ModuleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfos, error) {
	out := new(PluginInfos)
	err := c.cc.Invoke(ctx, Service_ModuleInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Request(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, Service_Request_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) MiddlewaresRequest(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error) {
	out := new(MiddlewareResponse)
	err := c.cc.Invoke(ctx, Service_MiddlewaresRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) MiddlewaresResponse(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error) {
	out := new(MiddlewareResponse)
	err := c.cc.Invoke(ctx, Service_MiddlewaresResponse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CheckMiddlewareForApi(ctx context.Context, in *MiddlewareInfoRequest, opts ...grpc.CallOption) (*MiddlewareInfoResponse, error) {
	out := new(MiddlewareInfoResponse)
	err := c.cc.Invoke(ctx, Service_CheckMiddlewareForApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	ModuleInfo(context.Context, *Empty) (*PluginInfos, error)
	Request(context.Context, *HttpRequest) (*HttpResponse, error)
	MiddlewaresRequest(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)
	MiddlewaresResponse(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)
	CheckMiddlewareForApi(context.Context, *MiddlewareInfoRequest) (*MiddlewareInfoResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) ModuleInfo(context.Context, *Empty) (*PluginInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleInfo not implemented")
}
func (UnimplementedServiceServer) Request(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedServiceServer) MiddlewaresRequest(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MiddlewaresRequest not implemented")
}
func (UnimplementedServiceServer) MiddlewaresResponse(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MiddlewaresResponse not implemented")
}
func (UnimplementedServiceServer) CheckMiddlewareForApi(context.Context, *MiddlewareInfoRequest) (*MiddlewareInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMiddlewareForApi not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_ModuleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ModuleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ModuleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ModuleInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Request(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_MiddlewaresRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).MiddlewaresRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_MiddlewaresRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).MiddlewaresRequest(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_MiddlewaresResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).MiddlewaresResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_MiddlewaresResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).MiddlewaresResponse(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CheckMiddlewareForApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CheckMiddlewareForApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CheckMiddlewareForApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CheckMiddlewareForApi(ctx, req.(*MiddlewareInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModuleInfo",
			Handler:    _Service_ModuleInfo_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _Service_Request_Handler,
		},
		{
			MethodName: "MiddlewaresRequest",
			Handler:    _Service_MiddlewaresRequest_Handler,
		},
		{
			MethodName: "MiddlewaresResponse",
			Handler:    _Service_MiddlewaresResponse_Handler,
		},
		{
			MethodName: "CheckMiddlewareForApi",
			Handler:    _Service_CheckMiddlewareForApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
