// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: notice_send.proto

package grpc_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoticeSend_Send_FullMethodName = "/NoticeSend/Send"
)

// NoticeSendClient is the client API for NoticeSend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoticeSendClient interface {
	Send(ctx context.Context, in *NoticeSendReq, opts ...grpc.CallOption) (*NoticeSendResp, error)
}

type noticeSendClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeSendClient(cc grpc.ClientConnInterface) NoticeSendClient {
	return &noticeSendClient{cc}
}

func (c *noticeSendClient) Send(ctx context.Context, in *NoticeSendReq, opts ...grpc.CallOption) (*NoticeSendResp, error) {
	out := new(NoticeSendResp)
	err := c.cc.Invoke(ctx, NoticeSend_Send_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeSendServer is the server API for NoticeSend service.
// All implementations must embed UnimplementedNoticeSendServer
// for forward compatibility
type NoticeSendServer interface {
	Send(context.Context, *NoticeSendReq) (*NoticeSendResp, error)
	mustEmbedUnimplementedNoticeSendServer()
}

// UnimplementedNoticeSendServer must be embedded to have forward compatible implementations.
type UnimplementedNoticeSendServer struct {
}

func (UnimplementedNoticeSendServer) Send(context.Context, *NoticeSendReq) (*NoticeSendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedNoticeSendServer) mustEmbedUnimplementedNoticeSendServer() {}

// UnsafeNoticeSendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoticeSendServer will
// result in compilation errors.
type UnsafeNoticeSendServer interface {
	mustEmbedUnimplementedNoticeSendServer()
}

func RegisterNoticeSendServer(s grpc.ServiceRegistrar, srv NoticeSendServer) {
	s.RegisterService(&NoticeSend_ServiceDesc, srv)
}

func _NoticeSend_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeSendServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeSend_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeSendServer).Send(ctx, req.(*NoticeSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NoticeSend_ServiceDesc is the grpc.ServiceDesc for NoticeSend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoticeSend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NoticeSend",
	HandlerType: (*NoticeSendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _NoticeSend_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notice_send.proto",
}
