blank_issues_enabled: false
contact_links:
  - name: APINTO Dashboard Discussion Forum
    url: https://github.com/eolinker/apinto-dashboard/discussions
    about: Please ask and answer questions here.