// Code generated by MockGen. DO NOT EDIT.
// Source: warn/warn.go

// Package mock_warn is a generated GoMock package.
package mock_warn

import (
	context "context"
	reflect "reflect"
	time "time"

	warn_model "github.com/eolinker/apinto-dashboard/modules/warn/warn-model"
	gomock "github.com/golang/mock/gomock"
)

// MockIWarnStrategyService is a mock of IWarnStrategyService interface.
type MockIWarnStrategyService struct {
	ctrl     *gomock.Controller
	recorder *MockIWarnStrategyServiceMockRecorder
}

// MockIWarnStrategyServiceMockRecorder is the mock recorder for MockIWarnStrategyService.
type MockIWarnStrategyServiceMockRecorder struct {
	mock *MockIWarnStrategyService
}

// NewMockIWarnStrategyService creates a new mock instance.
func NewMockIWarnStrategyService(ctrl *gomock.Controller) *MockIWarnStrategyService {
	mock := &MockIWarnStrategyService{ctrl: ctrl}
	mock.recorder = &MockIWarnStrategyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWarnStrategyService) EXPECT() *MockIWarnStrategyServiceMockRecorder {
	return m.recorder
}

// CreateWarnStrategy mocks base method.
func (m *MockIWarnStrategyService) CreateWarnStrategy(ctx context.Context, namespaceId, userId int, input *warn_model.WarnStrategy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWarnStrategy", ctx, namespaceId, userId, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWarnStrategy indicates an expected call of CreateWarnStrategy.
func (mr *MockIWarnStrategyServiceMockRecorder) CreateWarnStrategy(ctx, namespaceId, userId, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWarnStrategy", reflect.TypeOf((*MockIWarnStrategyService)(nil).CreateWarnStrategy), ctx, namespaceId, userId, input)
}

// DeleteWarnStrategy mocks base method.
func (m *MockIWarnStrategyService) DeleteWarnStrategy(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWarnStrategy", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWarnStrategy indicates an expected call of DeleteWarnStrategy.
func (mr *MockIWarnStrategyServiceMockRecorder) DeleteWarnStrategy(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWarnStrategy", reflect.TypeOf((*MockIWarnStrategyService)(nil).DeleteWarnStrategy), ctx, uuid)
}

// DeleteWarnStrategyByPartitionId mocks base method.
func (m *MockIWarnStrategyService) DeleteWarnStrategyByPartitionId(ctx context.Context, namespaceId, partitionId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWarnStrategyByPartitionId", ctx, namespaceId, partitionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWarnStrategyByPartitionId indicates an expected call of DeleteWarnStrategyByPartitionId.
func (mr *MockIWarnStrategyServiceMockRecorder) DeleteWarnStrategyByPartitionId(ctx, namespaceId, partitionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWarnStrategyByPartitionId", reflect.TypeOf((*MockIWarnStrategyService)(nil).DeleteWarnStrategyByPartitionId), ctx, namespaceId, partitionId)
}

// UpdateWarnStrategy mocks base method.
func (m *MockIWarnStrategyService) UpdateWarnStrategy(ctx context.Context, namespaceId, userId int, input *warn_model.WarnStrategy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWarnStrategy", ctx, namespaceId, userId, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWarnStrategy indicates an expected call of UpdateWarnStrategy.
func (mr *MockIWarnStrategyServiceMockRecorder) UpdateWarnStrategy(ctx, namespaceId, userId, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWarnStrategy", reflect.TypeOf((*MockIWarnStrategyService)(nil).UpdateWarnStrategy), ctx, namespaceId, userId, input)
}

// UpdateWarnStrategyStatus mocks base method.
func (m *MockIWarnStrategyService) UpdateWarnStrategyStatus(ctx context.Context, uuid string, isEnable bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWarnStrategyStatus", ctx, uuid, isEnable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWarnStrategyStatus indicates an expected call of UpdateWarnStrategyStatus.
func (mr *MockIWarnStrategyServiceMockRecorder) UpdateWarnStrategyStatus(ctx, uuid, isEnable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWarnStrategyStatus", reflect.TypeOf((*MockIWarnStrategyService)(nil).UpdateWarnStrategyStatus), ctx, uuid, isEnable)
}

// WarnStrategyAll mocks base method.
func (m *MockIWarnStrategyService) WarnStrategyAll(ctx context.Context, namespaceId, status int) ([]*warn_model.WarnStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WarnStrategyAll", ctx, namespaceId, status)
	ret0, _ := ret[0].([]*warn_model.WarnStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WarnStrategyAll indicates an expected call of WarnStrategyAll.
func (mr *MockIWarnStrategyServiceMockRecorder) WarnStrategyAll(ctx, namespaceId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnStrategyAll", reflect.TypeOf((*MockIWarnStrategyService)(nil).WarnStrategyAll), ctx, namespaceId, status)
}

// WarnStrategyByUuid mocks base method.
func (m *MockIWarnStrategyService) WarnStrategyByUuid(ctx context.Context, namespaceId int, uuid string) (*warn_model.WarnStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WarnStrategyByUuid", ctx, namespaceId, uuid)
	ret0, _ := ret[0].(*warn_model.WarnStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WarnStrategyByUuid indicates an expected call of WarnStrategyByUuid.
func (mr *MockIWarnStrategyServiceMockRecorder) WarnStrategyByUuid(ctx, namespaceId, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnStrategyByUuid", reflect.TypeOf((*MockIWarnStrategyService)(nil).WarnStrategyByUuid), ctx, namespaceId, uuid)
}

// WarnStrategyListPage mocks base method.
func (m *MockIWarnStrategyService) WarnStrategyListPage(ctx context.Context, namespaceId int, query *warn_model.QueryWarnStrategyParam) ([]*warn_model.WarnStrategy, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WarnStrategyListPage", ctx, namespaceId, query)
	ret0, _ := ret[0].([]*warn_model.WarnStrategy)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WarnStrategyListPage indicates an expected call of WarnStrategyListPage.
func (mr *MockIWarnStrategyServiceMockRecorder) WarnStrategyListPage(ctx, namespaceId, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnStrategyListPage", reflect.TypeOf((*MockIWarnStrategyService)(nil).WarnStrategyListPage), ctx, namespaceId, query)
}

// MockIWarnHistoryService is a mock of IWarnHistoryService interface.
type MockIWarnHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockIWarnHistoryServiceMockRecorder
}

// MockIWarnHistoryServiceMockRecorder is the mock recorder for MockIWarnHistoryService.
type MockIWarnHistoryServiceMockRecorder struct {
	mock *MockIWarnHistoryService
}

// NewMockIWarnHistoryService creates a new mock instance.
func NewMockIWarnHistoryService(ctrl *gomock.Controller) *MockIWarnHistoryService {
	mock := &MockIWarnHistoryService{ctrl: ctrl}
	mock.recorder = &MockIWarnHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWarnHistoryService) EXPECT() *MockIWarnHistoryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWarnHistoryService) Create(ctx context.Context, namespaceId, partitionId int, infos ...*warn_model.WarnHistoryInfo) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, namespaceId, partitionId}
	for _, a := range infos {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIWarnHistoryServiceMockRecorder) Create(ctx, namespaceId, partitionId interface{}, infos ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, namespaceId, partitionId}, infos...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWarnHistoryService)(nil).Create), varargs...)
}

// QueryList mocks base method.
func (m *MockIWarnHistoryService) QueryList(ctx context.Context, namespaceId, partitionId, pageNum, pageSize int, startTime, endTime time.Time, name string) ([]*warn_model.WarnHistoryInfo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryList", ctx, namespaceId, partitionId, pageNum, pageSize, startTime, endTime, name)
	ret0, _ := ret[0].([]*warn_model.WarnHistoryInfo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryList indicates an expected call of QueryList.
func (mr *MockIWarnHistoryServiceMockRecorder) QueryList(ctx, namespaceId, partitionId, pageNum, pageSize, startTime, endTime, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryList", reflect.TypeOf((*MockIWarnHistoryService)(nil).QueryList), ctx, namespaceId, partitionId, pageNum, pageSize, startTime, endTime, name)
}
