zone: zh_cn
default: upstream
apinto:
  - "http://172.18.189.43:9400"
port: 8080
user_details:
  type: file
  file: ./account.yaml
professions:

  - name: services
    profession: service
    i18n_name:
      zh_cn: 服务
      en_us: services
  - name: upstreams
    profession: upstream
    i18n_name:
      zh_cn: 上游
      en_us: upstreams
  - name: discoveries
    profession: discovery
    i18n_name:
      zh_cn: 服务发现
      en_us: discoveries
  - name: auths
    profession: auth
    i18n_name:
      zh_cn: 鉴权
      en_us: auths
  - name: outputs
    profession: output
    i18n_name:
      zh_cn: 输出
      en_us: outputs