id: "influxdb.apinto.com"
name: "influxdb"
cname: "InfluxDB配置"
resume: "配置InfluxDB v2服务端信息，InfluxDB是监控告警的数据源之一。"
version: "v1.0.0"
icon: "监控告警.png"
driver: "dynamic.apinto.com"
front: template
navigation: "navigation.system"
group_id: "monitor"
define:  # 动态模块定义
  profession: output
  drivers:
    - name: influxdbv2
      title: InfluxDB-V2
  skill: Influx-Output
  fields:
    - name: title           # 定义从响应中对应字段中获取显示值
      title: 名称
    - name: id
      title: ID
    - name: driver
      title: 驱动名称
    - name: description
      title: 描述
  render:
    influxdbv2: |
      {
          "type":"object",
          "properties":{
              "scopes":{
                  "type":"array",
                  "title":"作用范围",
                  "x-decorator":"FormItem",
                  "x-component":"ArrayItems",
                  "x-decorator-props":{
                      "labelCol":6,
                      "wrapperCol":10
                  },
                  "name":"scopes",
                  "x-index":0,
                  "required":true,
                  "items":{
                      "type":"void",
                      "x-component":"Space",
                      "properties":{
                          "sort":{
                              "type":"void",
                              "x-decorator":"FormItem",
                              "x-component":"ArrayItems.SortHandle",
                              "name":"sort",
                              "x-index":0
                          },
                          "select":{
                              "type":"string",
                              "x-decorator":"FormItem",
                              "x-component":"Select",
                              "enum":[
                                  {
                                      "label":"监控",
                                      "value":"monitor"
                                  }
                              ],
                              "name":"select",
                              "x-index":1
                          },
                          "remove":{
                              "type":"void",
                              "x-decorator":"FormItem",
                              "x-component":"ArrayItems.Remove",
                              "name":"remove",
                              "x-index":2
                          }
                      }
                  },
                  "properties":{
                      "add":{
                          "type":"void",
                          "title":"添加条目",
                          "x-component":"ArrayItems.Addition",
                          "x-component-props":{
                              "defaultValue":"monitor"
                          },
                          "name":"add",
                          "x-index":0
                      }
                  }
              },
              "url":{
                  "type":"string",
                  "title":"URL",
                  "x-decorator":"FormItem",
                  "x-component":"Input",
                  "x-validator":"url",
                  "x-component-props":{

                  },
                  "x-decorator-props":{
                      "labelCol":6,
                      "wrapperCol":10
                  },
                  "name":"url",
                  "x-index":1,
                  "required":true
              },
              "org":{
                  "type":"string",
                  "title":"Org",
                  "x-decorator":"FormItem",
                  "x-component":"Input",
                  "x-validator":[

                  ],
                  "x-component-props":{

                  },
                  "x-decorator-props":{
                      "labelCol":6,
                      "wrapperCol":10
                  },
                  "name":"org",
                  "x-index":2,
                  "required":true
              },
              "bucket":{
                  "type":"string",
                  "title":"Bucket",
                  "x-decorator":"FormItem",
                  "x-component":"Input",
                  "x-validator":[

                  ],
                  "x-component-props":{

                  },
                  "x-decorator-props":{
                      "labelCol":6,
                      "wrapperCol":10
                  },
                  "name":"bucket",
                  "required":true,
                  "x-index":3
              },
              "token":{
                  "type":"string",
                  "title":"Token",
                  "x-decorator":"FormItem",
                  "x-component":"Input",
                  "x-validator":[

                  ],
                  "x-component-props":{

                  },
                  "x-decorator-props":{
                      "labelCol":6,
                      "wrapperCol":10
                  },
                  "name":"token",
                  "required":true,
                  "x-index":4
              }
          }
      }
