-
  content_type: application/json
  body: |-
    {
        "msg":"很抱歉，$api 暂停服务，请稍候再试！"
    }
-
  content_type: application/xml
  body: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <msg>很抱歉，$api 暂停服务，请稍候再试！</msg>
-
  content_type: text/html
  body: "<p> 很抱歉，$api 暂停服务，请稍候再试！</p>"